name: Release bundle for internal test with generating release APK

on:
  workflow_dispatch:  # allows manual run via Actions tab
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Restore playstore.keystore.jks
        run: echo "$KEYSTORE_FILE" | base64 -d > app/playstore.keystore.jks

      - name: Build release AAB
        run: |
          ./gradlew bundleRelease \
            -PSIGNING_KEY_ALIAS="${SIGNING_KEY_ALIAS}" \
            -PKEYSTORE_PASSWORD="${KEYSTORE_PASSWORD}" \
            -PKEYSTORE_FILE=app/playstore.keystore.jks \
            -PSIGNING_KEY_PASSWORD="${SIGNING_KEY_PASSWORD}"
      
      - name: Build release APK
        run: |
          ./gradlew assembleRelease \
            -PSIGNING_KEY_ALIAS="${SIGNING_KEY_ALIAS}" \
            -PKEYSTORE_PASSWORD="${KEYSTORE_PASSWORD}" \
            -PKEYSTORE_FILE=app/playstore.keystore.jks \
            -PSIGNING_KEY_PASSWORD="${SIGNING_KEY_PASSWORD}"


      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/*.aab

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
